global:
  scrape_interval: 5s

  # How frequently to evaluate rules.
  evaluation_interval: 30s

scrape_configs:
  - job_name: dummy-app
    honor_labels: true
    static_configs:
      - targets: ["dummycontainer:4567"]

